
service: testserverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  lambdaHashingVersion: "20201221"

functions:
  get_all_rates:
    handler: handler.get_all_rates
    environment:
      COIN: dai
      RPC_URL: https://mainnet.infura.io/v3
      API_KEY: 4cd98623d90d401ca984c02080c6bf72
      UNISWAP_GET_RATE_WALLET: '0xC0DcE374F9aC0607B432Be0b3439c5Dc84c8f985'
      EXCHANGE_GET_RATE_CONTRACT: '0x1603557c3f7197df2e'

  get_rate:
    handler: handler.get_rate
    events:
      - http:
          path: get_rate
          method: GET

  send_data:
    handler: handler.send_data
    events:
      - http:
          path: send_data
          method: GET

  receive_data:
    handler: handler.receive_data
    events:
      - http:
          path: receive_data
          method: GET
  
